### ISSUE TITLE
[ibm-telco] Failed to download kubeconfig 

### ISSUE THREAD

**Issue by maheshd2** [redhat-ztp/ztp-cluster-deploy#156]
With the master branch, we are seeing following error when we try downloading the kubeconfig, please let us know what could be the issue here.

```
[root@vcuhost site-packages]# aicli download "kubeconfig"  controlplane-cluster-1 --path /home/cp4na_automation/controlplane-cluster-1/ztp/
Downloading Kubeconfig for Cluster controlplane-cluster-1 in /home/cp4na_automation/controlplane-cluster-1/ztp//kubeconfig.controlplane-cluster-1
Traceback (most recent call last):
  File "/usr/local/bin/aicli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/ailib/cli.py", line 552, in cli
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/ailib/cli.py", line 180, in download_kubeconfig
    ai.download_kubeconfig(args.cluster, args.path)
  File "/usr/local/lib/python3.6/site-packages/ailib/__init__.py", line 235, in download_kubeconfig
    _preload_content=False)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 794, in download_cluster_files
    (data) = self.download_cluster_files_with_http_info(cluster_id, file_name, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/api/installer_api.py", line 882, in download_cluster_files_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 330, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 161, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/api_client.py", line 351, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 238, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/assisted_service_client/rest.py", line 228, in request
    raise ApiException(http_resp=r)
assisted_service_client.rest.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Thu, 19 Aug 2021 10:54:56 GMT', 'Content-Type': 'application/octet-stream', 'Content-Length': '90', 'Connection': 'keep-alive'})
HTTP response body: b'{"code":403,"message":"File \'kubeconfig-noingress\' is accessible only for cluster owners"}'
```

**Comment by yrobla** [comment]
Cluster deployment for master branch is not performed via aicli, but using ACM. So I cannot validate your issues on master branch. You should continue using the stable branch for your integration, or perform a fork of the repo , to add your custom changes to it if needed.
